#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=16,walltime=12:00:00

## modules
echo "Loading modules"
module unload python
module load dipy/dev
module load nodejs
echo "Finished loading modules"

export PYTHONPATH=/N/u/brlife/git/nibabel:$PYTHONPATH

echo "setting miniconda path..."
unset PYTHONPATH
export PATH=/N/u/gberto/Karst/miniconda2/bin:$PATH 

#execute app
./run.sh

ret=$?
if [ ! $ret -eq 0 ]; then
	exit $ret
fi

#removing files
rm *.trk -f
rm *.tck -f
rm *.nii.gz -f
rm -r tractograms_directory -f
rm -r examples_directory* -f
rm kdt -f
rm prototypes.npy -f
rm -r aligned_ROIs -f
rm -r templates -f
rm distance* -f

echo "Complete"
