#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=16,vmem=31gb,walltime=12:00:00

set -e
set -x

#execute app
#./run.sh
SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://giuliaberto/classifyber:1.2 ./run.sh

ret=$?
if [ ! $ret -eq 0 ]; then
	exit $ret
fi

#removing files
rm *.tck -f
rm *.nii.gz -f
rm -r tractograms_directory -f
rm -r examples_directory* -f
rm kdt -f
rm prototypes.npy -f
rm -r aligned_ROIs -f
rm -r templates -f
rm distance* -f

echo "Complete"
