#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=16,vmem=31gb,walltime=12:00:00

set -e
set -x

export FREESURFER_LICENSE="hayashis@iu.edu 29511 *CPmh9xvKQKHE FSg0ijTusqaQc"
echo $FREESURFER_LICENSE > license.txt

#convert some files
fsDir=$(jq -r .fsDir config.json)
if [ $fsDir != "null" ];then
    singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/connectome_workbench:1.4.2b ./convert_files.sh
fi

#execute app
#./run.sh
SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:0.16.0 ./run.sh

ret=$?
if [ ! $ret -eq 0 ]; then
	exit $ret
fi

#removing files
rm *.tck -f
rm *.nii.gz -f
rm -r tractograms_directory -f
rm -r examples_directory* -f
rm kdt -f
rm prototypes.npy -f
rm -r aligned_ROIs -f
rm -r templates -f
rm distance* -f

echo "Complete"
